### ISSUE TITLE
Cant Startup Bot

### ISSUE THREAD

**Issue by noxish** [BramEsendam/DiscordBotTemplate#9]
Hi, first thing i want say, its an amazing project :) 

but i cant startup the bot after i changed Constants and did the EFCore Migration, always get the following Disconnected error

0 Disconnected with the reason A task was canceled

Debug Console Output:
![image](https://user-images.githubusercontent.com/3374229/150787200-6ed02640-3ac6-41e5-a556-37a9f568cabb.png)

Discord Output:
![image](https://user-images.githubusercontent.com/3374229/150787314-fb1d3750-31c1-4b7d-ad61-b6edbff7eb7b.png)

**Comment by BrammyS** [comment]
Sadly this project is out of date.
It has not been updated in a long time, so I can't say what exactly is going on.

I personally don't have the time to update the template at the moment, so I'll probably end up archiving the repo.
But feel free to create a pull request if you find out what the issue was! <3

**Comment by noxish** [comment]
Hey @BrammyS i will try to update it,
dont archive it, its awesome :)
